### ISSUE TITLE
Task automation for the repo

### ISSUE THREAD

**Issue by vados-cosmonic** [bytecodealliance/StarlingMonkey#179]
The  instructions in the README are certainly very easy to follow at present, but I wanted to add some leverage there with a top level `Make` file --  and want to gauge interest/see if that's something people would be open to.

GNU `make` is great and all, but to avoid the pitfalls and complexity that can sometimes come with it, I'd *like* to do one of the following:

- Create a top level Rust workspace so we can leverage [`cargo xtask`](https://github.com/matklad/cargo-xtask) (no extra dependencies, but would require the Rust toolchain more strongly -- e.g. we could update the documentation to run xtasks that run `cmake` underneath)

- Use a more general task runner like [`just`](https://github.com/casey/just)

My goals with this change are to add a little leverage to enable easier setup and ongoing usage for devs -- whether it's explicitly checking whether dependencies are downloaded, checking/printing versions of all involved tooling, orchestrating multi-language build targets, etc.

**Comment by tschneidereit** [comment]
I agree that more automation for some of the core bootstrapping and development loop tasks would be great, yes!

At the same time, I'd be a bit wary of adding additional requirements that have to be met before anything else happens. Right now, that's just `CMake` and `rustup`, and arguably we could eliminate the latter if we wanted to.

One option to perhaps explore is whether [CMake workflows](https://cmake.org/cmake/help/latest/manual/cmake.1.html#workflow-mode) get us sufficiently far: combined with presets, they would allow us to reduce the "clone the repo --> have tests passing" process to something like
1. install CMake and rustup
2. clone the repo
3. run `cmake --workflow --preset test-debug`

After these steps, we'd have a `cmake-build-debug` folder with a build that has passed tests.

**Comment by t3hmrman** [comment]
> At the same time, I'd be a bit wary of adding additional requirements that have to be met before anything else happens.

Yeah I definitely understand/agree with this -- one thing I want to note is that `cargo xtask` is actually not a separate tool -- it's a convention (and `Cargo.toml` config) rather than something you need to install!

So running an `xtask` looks like this:

```
cargo xtask deploy
``


> Right now, that's just CMake and rustup, and arguably we could eliminate the latter if we wanted to.

Ah did I miss this? When you say `rustup` do you mean *literally* `rustup` and not a-version-of-the-rust-toolchain? 

Given the Rust bits, I was assuming we could depend on `cargo` being present/installed. If we can't then `cargo xtask` is certainly a new dep.

> One option to perhaps explore is whether [CMake workflows](https://cmake.org/cmake/help/latest/manual/cmake.1.html#workflow-mode) get us sufficiently far: combined with presets, they would allow us to reduce the "clone the repo --> have tests passing" process to something like

TIL about CMake workflows! I'm not so familiar with CMake but I guess the two no-dep choices are:

- CMake workflows
- `cargo xtask`

I like the `xtask` mostly because I'm more familiar with Rust than CMake, and since it's a fully general language we can make use of the Rust ecosystem (for better or worse, complexity wise!).

What do you think -- if CMake workflows looks more exciting I can take a stab at building it out to see how it would work, but IMO we could orchestrate CMake itself (and optionally even install it, if it's missing) from `xtask`.

**Comment by vados-cosmonic** [comment]
> At the same time, I'd be a bit wary of adding additional requirements that have to be met before anything else happens.

Yeah I definitely understand/agree with this -- one thing I want to note is that `cargo xtask` is actually not a separate tool -- it's a convention (and `Cargo.toml` config) rather than something you need to install!

So running an `xtask` looks like this:

```
cargo xtask deploy
```


> Right now, that's just CMake and rustup, and arguably we could eliminate the latter if we wanted to.

Ah did I miss this? When you say `rustup` do you mean *literally* `rustup` and not a-version-of-the-rust-toolchain-is-installed? 

Given the Rust bits, I was assuming we could depend on `cargo` being present/installed. If we can't then `cargo xtask` is certainly a new dep.

> One option to perhaps explore is whether [CMake workflows](https://cmake.org/cmake/help/latest/manual/cmake.1.html#workflow-mode) get us sufficiently far: combined with presets, they would allow us to reduce the "clone the repo --> have tests passing" process to something like

TIL about CMake workflows! I'm not so familiar with CMake but I guess the two no-dep choices are:

- CMake workflows
- `cargo xtask`

I like the `xtask` mostly because I'm more familiar with Rust than CMake, and since it's a fully general language we can make use of the Rust ecosystem (for better or worse, complexity wise!).

What do you think -- if CMake workflows looks more exciting I can take a stab at building it out to see how it would work, but IMO we could orchestrate CMake itself (and optionally even install it, if it's missing) from `xtask`.

**Comment by andreiltd** [comment]
Oh, I only now saw this. I've been maintaining a `justfile` for myself but maybe someone can find it useful too. I pushed it here:
https://github.com/bytecodealliance/StarlingMonkey/pull/180

`just` has pretty much become the standard nowadays. +1 from me :)

**Comment by guybedford** [comment]
I think the combination of CMake and an optional Just file would work well.

With regards to introducing a new dependency - I would recommend we make Just entirely optional for convenience, and just note it at the end of the getting started what the sugars are.

I don't know enough about CMake workflows to make a judgement call, but overall I like the command recipe model combined with a caching task runner model and would favour Just over xtask and CMake workflows.

**Comment by vados-cosmonic** [comment]
OK great it seems like we're all at least partially aligned on `just` moving forward, in an optional manner (with some mention in the README).

@tschneidereit how does that sound to you? 

If so, we can review @andreiltd 's existing PR and then I've got some additions I'd like to make which I'll open a separate PR for (but we can close this issue at the very least!)
