### ISSUE TITLE
Possible incorrect event loop interest for blob implementation

### ISSUE THREAD

**Issue by guybedford** [bytecodealliance/StarlingMonkey#186]
The new immediate steam tasks always increase event loop interest.

I believe this is incorrect, because event loop interest is purely about the request / response lifecycle, and if one happened to be constructing blobs on immediate tasks in a recursive loop that are entirely irrelevant to the request / response lifecycle, these blob immediates should not drive interest at all.

Posted https://github.com/bytecodealliance/StarlingMonkey/pull/185.

//cc @andreiltd

**Comment by andreiltd** [comment]
Is this fixed by https://github.com/bytecodealliance/StarlingMonkey/pull/185 or does it require further investigation?

**Comment by guybedford** [comment]
Resolved, thanks. Although I am getting a really strange error when trying to use this stuff in Fastly's build here - https://github.com/fastly/js-compute-runtime/pull/1070. A completely unrelated test case is failing even when none of the added code paths in that PR actually run for it. And it only happens in the release build not the debug build. Spent ages bisecting it and still can't figure it out...

**Comment by guybedford** [comment]
Yeah already spent 5 hours on it adding `abort()` statements into the `extract_body` blob path, and it randomly breaks inly on the stream ops, but again these are dead code paths! Unfortunately there's no minimal replication, and it also requires a Fastly API key to test. Perhaps we can arrange a pairing session on it sometime?

**Comment by andreiltd** [comment]
> Perhaps we can arrange a pairing session on it sometime?
Yeah sure!
