### ISSUE TITLE
Implement "immutable" headers guard

### ISSUE THREAD

**Issue by guybedford** [bytecodealliance/StarlingMonkey#78]
Fetch requests should return a response with headers marked with an `"immutable"` guard, where `check_guard` should always fail. In the Fetch spec it appears this is only ever done for responses.

Would this make sense to consider as an addition? Or is another implementation mechanism planned?

**Comment by guybedford** [comment]
Or is this functionality fully covered by the `HttpHeadersReadOnly` handle?

**Comment by tschneidereit** [comment]
It is indeed fully covered by `HttpHeadersReadOnly`, yes. I'm not opposed to additionally use the guard concept for this, though that'd obviously cause duplication.

I'd definitely prefer to not replace the type system enforcement of read-only-ness with a dynamic check completely though: introducing the type hierarchy has definitely helped me fix various bugs.

**Comment by guybedford** [comment]
Resolved in #108.
