### ISSUE TITLE
Run all tests in debug mode in CI

### ISSUE THREAD

**Issue by tschneidereit** [bytecodealliance/StarlingMonkey#93]
Running the WPT suite locally I noticed that some of the tests that pass in release mode hit asserts in the debug build. To avoid a proliferation of this, we should ensure that we run tests in debug mode, too.

To avoid making CI take way too long, we could mark more tests as `SLOW`, or perhaps even introduce a new `DEBUG-SLOW` annotation to skip them only in debug builds.

Additionally, we can look into running the suite with some parallelization. That wouldn't be too hard, with the main issue being that we'd want to pipe outputs correctly to not have completely garbled logs.

**Comment by guybedford** [comment]
This was added in https://github.com/bytecodealliance/StarlingMonkey/pull/113.
